flags: {}
packages:
- '.'
- location:
    git: https://github.com/plaprade/haskoin.git
    commit: 46aa1697fc8f27db3fa739ca5df1a4d2e6e92c32
extra-deps:
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
resolver: lts-2.15
