flags: {}
packages:
- '.'
- location:
    git: https://github.com/plaprade/haskoin.git
    commit: 8ac65e53e7a9f31ad74ecd24805b17e21434d25a
extra-deps:
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
resolver: lts-2.15
