flags: {}
packages:
- '.'
- location:
    git: https://github.com/plaprade/haskoin.git
    commit: cffeae123e7480135998788842c2b6a7db37c51e
extra-deps:
- SafeSemaphore-0.10.1
- daemons-0.2.1
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- pbkdf-1.1.1.1
- esqueleto-2.2.7
resolver: lts-2.15
