resolver: lts-12.7
nix:
  packages:
    - autoconf
    - automake
    - libtool
    - secp256k1
extra-deps:
  - murmur3-1.0.3
  - github: haskoin/secp256k1-haskell
    commit: 9e4c89fada1dcbe7dc87806561d026ecdd9d7ee7
