resolver: lts-12.7
nix:
  packages:
    - autoconf
    - automake
    - libtool
    - secp256k1
extra-deps:
  - murmur3-1.0.3
  - github: haskoin/secp256k1-haskell
    commit: 97f1c4c69e78102df5191a2d49a08eacba52f3ad
