resolver: lts-6.15

flags: {}
packages:
- haskoin-core
- haskoin-node
- haskoin-wallet
extra-deps:
- daemons-0.2.1
- pbkdf-1.1.1.1
- secp256k1-0.4.6
- murmur3-1.0.3
### uncomment below for lts-7.18 compatibility
#- esqueleto-2.5.1
