# ZeroMQ socket on which to listen to. Either absolute path or relative to
# work-dir/network
zeromq-bind: "_env:ZEROMQ_BIND:ipc://hw-spv"
# Server mode. Can be either online or offline. In offline mode, the SPV
# daemon does not start and only the local wallet is available to query.
server-mode: "_env:SERVER_MODE:online"

# False positive rate for the bloom filters. 
bloom-false-positive: "_env:BLOOM_FALSE_POSITIVE:0.00001"
# How many addresses you want to pre-generate for each account.
address-gap: "_env:ADDRESS_GAP:10"

# Sqlite3 database connection information
database:
  database: "_env:SQLITE_DATABASE:hw-wallet.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:1"

# List of trusted bitcoin full-nodes to connect to.
bitcoin-full-nodes: 
  - host: "_env:BITCOIN_NODE:127.0.0.1"
    port: "_env:BITCOIN_PORT:18333"

# Haskoin working directory. Either absolute path or relative to $HOME
work-dir: "_env:HW_HOME:.hw"
# Log file name. Either absolute path or relative to work-dir/network
log-file: "_env:HW_LOGFILE:hw.log"
# PID file name. Either absolute path or relative to work-dir/network
pid-file: "_env:HW_PIDFILE:hw.pid"
# Compile time configuration value. Either absolute path or relative to
# work-dir/network. This value can not be set at runtime.
config-file: "_env:HW_SERVERCFG:server.yml"

